[tool.poetry]
name = "botwrapper"
version = "0.1.0"
description = ""
authors = ["nutakoooye <andrkool151@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tvmazetgbot = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
